apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: srashti
spec:
  replicas: 1  # Number of desired replicas/pods
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - name: frontend
        image:  976226188110.dkr.ecr.us-east-1.amazonaws.com/frontend-repo:latest
        ports:
        - containerPort: 3000  # Replace with the port your application listens on

 
