apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: srashti
spec:
  replicas: 1 # Number of desired replicas/pods
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: 976226188110.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
        ports:
        - containerPort: 3001  # Replace with the port your application listens on
---

# https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: backend-deployment
  namespace: srashti
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
 
