apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: srashti
spec:
  replicas: 1 # Number of desired replicas/pods
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: 976226188110.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
        ports:
        - containerPort: 3001  # Replace with the port your application listens on

 
